name: AFR Equity Notifier

on:
  schedule:
    # run every minute
    - cron: "* * * * *"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true    # so we can push seen.json later

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run notifier
        env:
          AFR_RSS_URL: ${{ secrets.AFR_RSS_URL }}
          KEYWORDS:    ${{ secrets.KEYWORDS }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:   ${{ secrets.SMTP_PORT }}
          SMTP_USER:   ${{ secrets.SMTP_USER }}
          SMTP_PASS:   ${{ secrets.SMTP_PASS }}
          EMAIL_TO:    ${{ secrets.EMAIL_TO }}
        run: python app.py

      - name: Commit updated seen.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add seen.json
          git commit -m "chore: update seen.json" || echo "No changes"
          git push
